version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306  
      - MYSQL_DATABASE=${NAME}
      - MYSQL_USER=${USER} 
      - MYSQL_PASSWORD=${PASSWORD}
      - MYSQL_ROOT_PASSWORD=root123
       #change to the password you want for user
    ports:
      - "3307:3306"
    volumes:
      - .setup.sql:/docker-entrypoint-initbd.d/setup.sql
  
  web:
    build: .
      # command: python manage.py runserver 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    container_name: docker_dir
    volumes:
      - .:/docker_dir
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db 

     